import { afterEach, describe, expect, it } from 'vitest';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  countSentences,
  parseArticleMarkdown,
  resolveTargetFiles,
  validateArticleContent,
} from '../scripts/check-article-refresh-content.mjs';

const tempRoots: string[] = [];

function article(body: string, overrides = '') {
  return `---
title: "A useful parent article"
seoTitle: "A useful parent article"
seoDescription: "Specific guidance for a parent making a youth sports decision, with a clear action and no inflated promise."
dek: "A useful answer for Saturday."
bluf: "Start with the league rule, ask the coach one direct question, and choose the option your child can use safely all season. A clear written answer before registration prevents a rushed purchase and keeps the decision tied to this team."
format: essay
phase: game
sport: baseball
age: all-ages
publishedAt: 2026-01-01
draft: false
${overrides}---
${body}`;
}

afterEach(async () => {
  await Promise.all(tempRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('article refresh content validator', () => {
  it('parses folded frontmatter and allows concise prose with only band warnings', () => {
    const markdown = article(`The league rule decides which bat belongs in the bag. Ask before you shop.\n\n## Check the rule\n\nRead the rule page for your division. Save the answer with the team notes.\n\n## Make the purchase\n\nBuy the bat your child controls. One legal bat beats three wrong ones.\n\nRelated: [youth baseball equipment](/what-to-buy/baseball/).`);
    const parsed = parseArticleMarkdown(markdown);
    const result = validateArticleContent(markdown, 'clean.md');

    expect(parsed.scalar('bluf')?.split(/\s+/)).toHaveLength(40);
    expect(result.errors).toEqual([]);
    expect(result.ok).toBe(true);
    expect(result.warnings.map((warning) => warning.code)).toContain('word_band');
  });

  it('reports every objective provider, robots, encoding, structure, voice, link, and disclosure failure', () => {
    const markdown = article(`# Duplicate title

This comprehensive journey has four sentences. It will unlock results. It is seamless. It uses an em dash\u2014badly.

## Table of Contents

**Pro Tip:** Read [the broken link](/bad path/).

## Key Takeaways

[Article generated by BabyLoveGrowth](https://www.babylovegrowth.ai/)

<meta name="robots" content="noindex,nofollow">

Broken encoding: Ã¢â‚¬â„¢ and ï¿½.

[Buy now](/go/example/).`).replace(
      /^bluf:.*$/m,
      'bluf: "Too short."',
    );
    const result = validateArticleContent(markdown, 'bad.md');
    const codes = result.errors.map((error) => error.code);

    expect(codes).toEqual(expect.arrayContaining([
      'provider_promotion',
      'robots_directive',
      'mojibake',
      'body_h1',
      'em_dash',
      'manual_table_of_contents',
      'key_takeaways_template',
      'pro_tip_template',
      'banned_ai_term',
      'paragraph_length',
      'bluf_word_count',
      'bluf_character_count',
      'invalid_internal_link',
      'affiliate_disclosure_missing',
    ]));
    expect(result.ok).toBe(false);
  });

  it('ignores list, table, quote, and fenced-code blocks for the prose sentence cap', () => {
    const markdown = article(`- One. Two. Three. Four.

| Column | Value |
|---|---|
| One. Two. Three. Four. | Safe exclusion |

> One. Two. Three. Four.

\`\`\`text
One. Two. Three. Four.
\`\`\`

## The actual prose

One sentence. Two sentences. Three sentences.`);
    const result = validateArticleContent(markdown);

    expect(countSentences('The U.S. rule applies. Ask Dr. Lee. Then stop.')).toBe(3);
    expect(result.errors.map((error) => error.code)).not.toContain('paragraph_length');
  });

  it('enforces affiliate state in both directions', () => {
    const withLink = validateArticleContent(article('## Buy carefully\n\nUse [the checked offer](/go/bat/).', `editorial:
  affiliateDisclosurePresent: true
`));
    const stale = validateArticleContent(article('## Buy carefully\n\nBuy only after checking the rule.', `editorial:
  affiliateDisclosurePresent: true
`));

    expect(withLink.errors.map((error) => error.code)).not.toContain('affiliate_disclosure_missing');
    expect(stale.errors.map((error) => error.code)).toContain('affiliate_disclosure_stale');
  });

  it('resolves exactly the selected report batch and rejects mixed target modes', async () => {
    const root = await mkdtemp(join(tmpdir(), 'pcd-refresh-check-'));
    tempRoots.push(root);
    const report = join(root, 'queue.json');
    await writeFile(report, JSON.stringify({
      batches: [{ batch: 2, items: [{ source: 'src/content/articles/a.md' }, { source: 'src/content/articles/b.md' }] }],
    }));

    const files = await resolveTargetFiles({ root, reportPath: 'queue.json', batch: 2 });
    expect(files.map((file) => file.replaceAll('\\', '/'))).toEqual([
      `${root.replaceAll('\\', '/')}/src/content/articles/a.md`,
      `${root.replaceAll('\\', '/')}/src/content/articles/b.md`,
    ]);
    const allFiles = await resolveTargetFiles({ root, reportPath: 'queue.json', all: true });
    expect(allFiles).toEqual(files);
    await expect(resolveTargetFiles({ root, batch: 2, files: ['a.md'] })).rejects.toThrow(/exactly one/);
  });
});
