import { afterEach, describe, expect, it, vi } from 'vitest';
import type { D1Database, ExecutionContext } from '@cloudflare/workers-types';
import {
  articleFingerprint,
  babyLoveArticleUrl,
  buildBabyLoveArticleMarkdown,
  handleBabyLoveWebhook,
  parseBabyLoveArticle,
  reconcileBabyLoveArticles,
  sanitizeExternalMarkdown,
  type BabyLoveEnv,
} from '../src/lib/babylove-growth';
import { makeFakeD1 } from './helpers/d1';

const LONG_BODY = `
# A provider heading

Youth sports can put parents in difficult moments. The useful response starts with curiosity, a calm question, and enough silence for a child to answer honestly.

This article gives parents a practical framework for separating their own emotions from the child's experience, choosing words that preserve the relationship, and deciding whether action is actually needed.
`.repeat(2);

const PAYLOAD = {
  id: 'article-123',
  title: 'What Parents Should Say After a Difficult Game',
  slug: 'what-to-say-after-a-difficult-game',
  content_markdown: LONG_BODY,
  meta_description: 'A practical guide for parents handling the ride home after a difficult youth sports game without damaging trust or turning the moment into a lecture.',
  excerpt: 'Calm, relationship-first guidance for the ride home after a difficult game.',
  language_code: 'en-US',
  created_at: '2026-08-01T12:00:00.000Z',
};

function executionContext(pending: Promise<unknown>[]): ExecutionContext {
  return {
    waitUntil(promise: Promise<unknown>) {
      pending.push(promise);
    },
    passThroughOnException() {},
  } as unknown as ExecutionContext;
}

function webhookRequest(body: string, headers: Record<string, string> = {}): Request {
  return new Request('https://parentcoachdesk.com/api/integrations/babylovegrowth/articles', {
    method: 'POST',
    headers: {
      authorization: 'Bearer webhook-test-token',
      'content-type': 'application/json',
      ...headers,
    },
    body,
  });
}

function env(db: unknown, overrides: Partial<BabyLoveEnv> = {}): BabyLoveEnv {
  return {
    PCD_OPS_DB: db as D1Database,
    BABYLOVE_WEBHOOK_TOKEN: 'webhook-test-token',
    BABYLOVE_AUTOPUBLISH_ENABLED: 'false',
    ...overrides,
  };
}

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('BabyLoveGrowth article normalization', () => {
  it('accepts direct and article-envelope payloads with stable fingerprints', async () => {
    const direct = parseBabyLoveArticle(PAYLOAD);
    const wrapped = parseBabyLoveArticle({ article: PAYLOAD });
    expect(wrapped).toEqual(direct);
    expect(await articleFingerprint(wrapped)).toBe(await articleFingerprint(direct));
    expect(direct.slug).toBe(PAYLOAD.slug);
    expect(direct.languageCode).toBe('en-us');
  });

  it('converts HTML when markdown is absent', () => {
    const article = parseBabyLoveArticle({
      ...PAYLOAD,
      content_markdown: undefined,
      content_html: `<h1>One title</h1><p>${LONG_BODY}</p>`,
    });
    expect(article.contentMarkdown).toContain('## One title');
    expect(article.contentMarkdown).not.toContain('<h1>');
  });

  it('removes active content, embedded images, and unsafe links while preserving later dividers', () => {
    const safe = sanitizeExternalMarkdown(`---
provider: value
---
# Main
<script>alert('x')</script>
![tracking pixel](data:image/png;base64,abc)
[bad](javascript:alert(1))

---

Keep this section.
`);
    expect(safe).not.toContain('provider: value');
    expect(safe).not.toContain('<script>');
    expect(safe).not.toContain('data:image');
    expect(safe).not.toContain('tracking pixel');
    expect(safe).not.toContain('javascript:');
    expect(safe).toContain('## Main');
    expect(safe).toContain('---\n\nKeep this section.');
  });

  it('removes only terminal provider promotion and canonicalizes same-site links', () => {
    const safe = sanitizeExternalMarkdown(`Useful context from [BabyLoveGrowth](https://www.babylovegrowth.ai/research).\n\n[Read the guide](https://parentcoachdesk.com/start-here)\n\n[Article generated by BabyLoveGrowth](https://www.babylovegrowth.ai/)`);

    expect(safe).toContain('[BabyLoveGrowth](https://www.babylovegrowth.ai/research)');
    expect(safe).toContain('[Read the guide](/start-here/)');
    expect(safe).not.toContain('Article generated by BabyLoveGrowth');
  });

  // BabyLoveGrowth's own cross-links used its fallback guess of
  // blog.parentcoachdesk.com/blog/<slug>/ before the webhook returned `link`
  // (see babyLoveArticleUrl). That subdomain has never resolved to this site.
  // Rewritten to the slug-only /blog/<slug>/ form that src/pages/blog/[slug].ts
  // resolves and 301s from, because the true phase-scoped route is not known
  // at ingest time for the *target* article.
  it('rewrites blog-subdomain cross-links to the slug redirect route', () => {
    const safe = sanitizeExternalMarkdown(`See [our other guide](https://blog.parentcoachdesk.com/blog/foo).`);
    expect(safe).toContain('[our other guide](/blog/foo/)');
    expect(safe).not.toContain('blog.parentcoachdesk.com');
  });

  it('rewrites blog-subdomain cross-links carrying a fragment', () => {
    const safe = sanitizeExternalMarkdown(`See [our other guide](https://blog.parentcoachdesk.com/blog/foo/#h).`);
    expect(safe).toContain('[our other guide](/blog/foo/#h)');
    expect(safe).not.toContain('blog.parentcoachdesk.com');
  });

  it('removes a provider title heading that duplicates the layout H1', () => {
    const article = parseBabyLoveArticle({
      ...PAYLOAD,
      title: 'What to Say After a Difficult Game',
      content_markdown: `# What to Say After a Difficult Game\n\n${LONG_BODY}`,
    });

    expect(article.contentMarkdown).not.toMatch(/^## What to Say After a Difficult Game/m);
    expect(article.contentMarkdown).toContain('Youth sports can put parents in difficult moments.');
  });

  it.each([
    [{ ...PAYLOAD, id: '../bad' }, 'invalid_article_id'],
    [{ ...PAYLOAD, title: 'short' }, 'invalid_title'],
    [{ ...PAYLOAD, language_code: 'fr' }, 'unsupported_language'],
    [{ ...PAYLOAD, content_markdown: 'too short' }, 'content_too_short'],
  ])('rejects invalid provider payloads', (payload, message) => {
    expect(() => parseBabyLoveArticle(payload)).toThrow(message);
  });

  // BabyLoveGrowth only stores `link` on its own domain or a subdomain of it,
  // and treats it as the article's live URL. This must be the real published
  // route, computed the same way publishReceipt derives `route`.
  it('builds the published article URL from the phase the title implies', () => {
    const article = parseBabyLoveArticle({
      ...PAYLOAD,
      title: 'Tryout Day Nerves: What to Say Beforehand',
      slug: 'tryout-day-nerves-what-to-say-beforehand',
      meta_description: 'How to prepare a kid for tryout day without adding pressure they did not ask for.',
    });
    expect(babyLoveArticleUrl(article)).toBe(
      'https://parentcoachdesk.com/drive-there/tryout-day-nerves-what-to-say-beforehand/',
    );
  });

  it('uses a deterministic date when the provider omits one', async () => {
    const withoutDate = { ...PAYLOAD, created_at: undefined };
    const first = parseBabyLoveArticle(withoutDate);
    const second = parseBabyLoveArticle(withoutDate);
    expect(first.createdAt).toBe('1970-01-01T00:00:00.000Z');
    expect(await articleFingerprint(first)).toBe(await articleFingerprint(second));
  });

  it('builds valid main-site frontmatter with provenance and audit-sized metadata', async () => {
    const article = parseBabyLoveArticle(PAYLOAD);
    const fingerprint = await articleFingerprint(article);
    const markdown = buildBabyLoveArticleMarkdown(article, fingerprint, '2026-08-01T13:00:00.000Z');
    const seoTitle = markdown.match(/^seoTitle: "(.+)"$/m)?.[1] ?? '';
    const seoDescription = markdown.match(/^seoDescription: "(.+)"$/m)?.[1] ?? '';

    // Lowered from 25/45 on 2026-09-08. seoTitle now prefers a complete phrase
    // over a longer fragment, and a complete headline sometimes lands at 22-24
    // characters. Padding those back over 25 produced filler like "A Parent
    // Code of Conduct: a parent guide", which is worse copy than a 44-character
    // title Google displays in full. See ensureWindow in babylove-growth.ts.
    expect(seoTitle.length).toBeGreaterThanOrEqual(22);
    expect(seoTitle.length).toBeLessThanOrEqual(40);
    expect(`${seoTitle} | Parent Coach Desk`.length).toBeGreaterThanOrEqual(42);
    expect(`${seoTitle} | Parent Coach Desk`.length).toBeLessThanOrEqual(60);
    expect(seoDescription.length).toBeGreaterThanOrEqual(140);
    expect(seoDescription.length).toBeLessThanOrEqual(160);
    expect(seoDescription).toMatch(/[.!?…]$/);
    expect(markdown).toMatch(/^bluf: ".{80,500}"$/m);
    expect(markdown).toContain('sport:');
    expect(markdown).toContain('age:');
    expect(markdown).toContain('hero:');
    expect(markdown).toContain('heroAlt:');
    expect(markdown).toContain('provider: "babylovegrowth"');
    expect(markdown).toContain('articleId: "article-123"');
    expect(markdown).toContain(`payloadSha256: "${fingerprint}"`);
    expect(markdown).toContain('draft: false');
    expect(markdown).toContain('status: published');
    expect(markdown).toContain('citationCheckPassed: false');
  });

  it('does not emit dangling metadata fragments from truncated provider copy', async () => {
    const article = parseBabyLoveArticle({
      ...PAYLOAD,
      meta_description: 'Wondering about the best choice for your kid? Discover the key differences to ensure your child gets the right fit for their',
      excerpt: 'Practical guidance for',
    });
    const markdown = buildBabyLoveArticleMarkdown(article, await articleFingerprint(article), '2026-08-01T13:00:00.000Z');
    const description = markdown.match(/^seoDescription: "(.+)"$/m)?.[1] ?? '';
    const dek = markdown.match(/^dek: "(.+)"$/m)?.[1] ?? '';

    expect(description).not.toMatch(/\b(?:for|their|and|the)\.?$/i);
    expect(dek).not.toMatch(/\b(?:for|their|and|the)\.?$/i);
    expect(description).toMatch(/[.!?…]$/);
    expect(dek).toMatch(/[.!?…]$/);
  });
});

describe('BabyLoveGrowth webhook boundary', () => {
  it('rejects unauthenticated, non-JSON, oversized, and malformed requests', async () => {
    const fake = makeFakeD1();
    const pending: Promise<unknown>[] = [];
    const ctx = executionContext(pending);

    const unauthorized = webhookRequest(JSON.stringify(PAYLOAD), { authorization: 'Bearer wrong' });
    expect((await handleBabyLoveWebhook(unauthorized, env(fake.db), ctx)).status).toBe(401);

    const nonJson = webhookRequest(JSON.stringify(PAYLOAD), { 'content-type': 'text/plain' });
    expect((await handleBabyLoveWebhook(nonJson, env(fake.db), ctx)).status).toBe(415);

    const oversized = webhookRequest('{}', { 'content-length': String(512 * 1024 + 1) });
    expect((await handleBabyLoveWebhook(oversized, env(fake.db), ctx)).status).toBe(413);

    const chunkedOversized = webhookRequest('x'.repeat(512 * 1024 + 1));
    expect((await handleBabyLoveWebhook(chunkedOversized, env(fake.db), ctx)).status).toBe(413);

    expect((await handleBabyLoveWebhook(webhookRequest('{'), env(fake.db), ctx)).status).toBe(400);
    expect(pending).toHaveLength(0);
  });

  it('acknowledges only after durable receipt processing completes', async () => {
    const fake = makeFakeD1();
    const pending: Promise<unknown>[] = [];
    const response = await handleBabyLoveWebhook(
      webhookRequest(JSON.stringify(PAYLOAD)),
      env(fake.db),
      executionContext(pending),
    );

    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({
      ok: true,
      accepted: true,
      replayed: false,
      success: true,
      link: babyLoveArticleUrl(parseBabyLoveArticle(PAYLOAD)),
    });
    expect(pending).toHaveLength(0);
    expect(fake.calls.some((call) =>
      call.sql.includes('UPDATE external_article_receipts') && call.params[0] === 'held'
    )).toBe(true);
  });

  // Renamed and re-pointed 2026-09-08. This asserted 503 until commit 3dc6132e
  // (2026-09-07) deliberately made our own credential failures answer 200:
  // BabyLoveGrowth reads 5xx as "this endpoint is unhealthy" and stops
  // delivering, which cost seven days of articles twice. The receipt is still
  // written as retryable_failure, so nothing is lost. See isOurCredentialFailure.
  it('keeps the delivery lane open when our GitHub token is dead', async () => {
    const fake = makeFakeD1();
    const fetchMock = vi.fn().mockResolvedValueOnce(new Response('unauthorized', { status: 401 }));
    vi.stubGlobal('fetch', fetchMock);

    const response = await handleBabyLoveWebhook(
      webhookRequest(JSON.stringify(PAYLOAD)),
      env(fake.db, {
        BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
        GITHUB_TOKEN: 'expired-github-token',
      }),
      executionContext([]),
    );

    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({ ok: true, accepted: false, deferred: true, error: 'github_read_401' });
    expect(fake.calls.some((call) =>
      call.sql.includes('UPDATE external_article_receipts')
      && call.params[0] === 'retryable_failure'
      && call.params[3] === 'github_read_401'
    )).toBe(true);
  });

  it('returns success only after GitHub commits an automatic publish', async () => {
    const fake = makeFakeD1();
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response('not found', { status: 404 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ commit: { sha: 'commit-webhook-123' } }), { status: 200 }));
    vi.stubGlobal('fetch', fetchMock);

    const response = await handleBabyLoveWebhook(
      webhookRequest(JSON.stringify(PAYLOAD)),
      env(fake.db, {
        BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
        GITHUB_TOKEN: 'github-test-token',
      }),
      executionContext([]),
    );

    expect(response.status).toBe(200);
    expect(await response.json()).toEqual({
      ok: true,
      accepted: true,
      replayed: false,
      success: true,
      link: babyLoveArticleUrl(parseBabyLoveArticle(PAYLOAD)),
    });
    expect(fetchMock).toHaveBeenCalledTimes(2);
    expect(fake.calls.some((call) =>
      call.sql.includes('UPDATE external_article_receipts') && call.params[0] === 'published'
    )).toBe(true);
  });

  it('does not schedule a second publish for an already-published fingerprint', async () => {
    const fake = makeFakeD1();
    const article = parseBabyLoveArticle(PAYLOAD);
    fake.queueFirst({
      id: 'receipt-existing',
      status: 'published',
      provider_article_id: article.id,
      payload_sha256: await articleFingerprint(article),
      received_at: '2026-08-01T13:00:00.000Z',
    });
    const pending: Promise<unknown>[] = [];
    const response = await handleBabyLoveWebhook(
      webhookRequest(JSON.stringify(PAYLOAD)),
      env(fake.db),
      executionContext(pending),
    );

    expect(await response.json()).toMatchObject({ ok: true, replayed: true });
    expect(pending).toHaveLength(0);
  });
});

describe('BabyLoveGrowth API reconciliation', () => {
  it('fetches full content and commits a regular article to the protected main branch', async () => {
    const fake = makeFakeD1();
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify({ articles: [{ id: PAYLOAD.id }] }), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ article: PAYLOAD }), { status: 200 }))
      .mockResolvedValueOnce(new Response('not found', { status: 404 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ commit: { sha: 'commit-123' } }), { status: 200 }));
    vi.stubGlobal('fetch', fetchMock);

    const result = await reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      BABYLOVE_API_KEY: 'api-test-key',
      GITHUB_TOKEN: 'github-test-token',
    }));

    expect(result).toEqual({ scanned: 1, published: 1, skipped: 0, failed: 0 });
    expect(fetchMock).toHaveBeenCalledTimes(4);
    expect(fetchMock.mock.calls[0][0]).toBe('https://api.babylovegrowth.ai/api/integrations/v1/articles');
    expect(fetchMock.mock.calls[0][1].headers['X-API-Key']).toBe('api-test-key');
    expect(fetchMock.mock.calls[2][0]).toContain('/contents/src/content/articles/what-to-say-after-a-difficult-game.md?ref=main');
    const putBody = JSON.parse(fetchMock.mock.calls[3][1].body);
    expect(putBody.branch).toBe('main');
    expect(Buffer.from(putBody.content, 'base64').toString('utf8')).toContain('externalSource:');
    expect(fake.calls.some((call) =>
      call.sql.includes('UPDATE external_article_receipts') && call.params[0] === 'published'
    )).toBe(true);
  });

  it('quarantines a slug collision instead of overwriting a human-authored article', async () => {
    const fake = makeFakeD1();
    const existingHumanArticle = Buffer.from('---\ntitle: Human article\ndraft: false\n---\nBody\n').toString('base64');
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify([{ id: PAYLOAD.id }]), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify(PAYLOAD), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ content: existingHumanArticle, sha: 'human-sha' }), { status: 200 }));
    vi.stubGlobal('fetch', fetchMock);

    const result = await reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      BABYLOVE_API_KEY: 'api-test-key',
      GITHUB_TOKEN: 'github-test-token',
    }));

    expect(result).toEqual({ scanned: 1, published: 0, skipped: 0, failed: 1 });
    expect(fetchMock).toHaveBeenCalledTimes(3);
    expect(fake.calls.some((call) =>
      call.sql.includes('UPDATE external_article_receipts')
      && call.params[0] === 'quarantined'
      && call.params[3] === 'slug_collision'
    )).toBe(true);
  });

  // Regression: reconciliation had never published a single article in its
  // life (zero source='api_reconciliation' rows in production as of
  // 2026-08-10) while six arrived by webhook. It accepted only a bare array or
  // { articles: [...] }, so any other envelope threw api_list_invalid before
  // it examined anything. That is how "Youth Basketball Drills: A Parent
  // Coach's Ready-to-Run Guide" sat in the provider dashboard and never
  // reached the repo.
  it.each([
    ['data', { data: [{ id: PAYLOAD.id }] }],
    ['items', { items: [{ id: PAYLOAD.id }] }],
    ['results', { results: [{ id: PAYLOAD.id }] }],
    ['records', { records: [{ id: PAYLOAD.id }] }],
    ['nested data.articles', { data: { articles: [{ id: PAYLOAD.id }] } }],
  ])('imports a missed article when the provider list arrives as %s', async (_label, listing) => {
    const fake = makeFakeD1();
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify(listing), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ article: PAYLOAD }), { status: 200 }))
      .mockResolvedValueOnce(new Response('not found', { status: 404 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ commit: { sha: 'commit-123' } }), { status: 200 }));
    vi.stubGlobal('fetch', fetchMock);

    const result = await reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      BABYLOVE_API_KEY: 'api-test-key',
      GITHUB_TOKEN: 'github-test-token',
    }));

    expect(result).toEqual({ scanned: 1, published: 1, skipped: 0, failed: 0 });
  });

  it.each([
    ['article_id', { articles: [{ article_id: PAYLOAD.id }] }],
    ['articleId', { articles: [{ articleId: PAYLOAD.id }] }],
    ['uuid', { articles: [{ uuid: PAYLOAD.id }] }],
  ])('identifies a listing item keyed by %s', async (_label, listing) => {
    const fake = makeFakeD1();
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(JSON.stringify(listing), { status: 200 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ article: PAYLOAD }), { status: 200 }))
      .mockResolvedValueOnce(new Response('not found', { status: 404 }))
      .mockResolvedValueOnce(new Response(JSON.stringify({ commit: { sha: 'commit-123' } }), { status: 200 }));
    vi.stubGlobal('fetch', fetchMock);

    const result = await reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      BABYLOVE_API_KEY: 'api-test-key',
      GITHUB_TOKEN: 'github-test-token',
    }));

    expect(result).toEqual({ scanned: 1, published: 1, skipped: 0, failed: 0 });
  });

  it('names the missing binding rather than reporting reconciliation_unavailable bare', async () => {
    const fake = makeFakeD1();
    await expect(reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      GITHUB_TOKEN: 'github-test-token',
    }))).rejects.toThrow(/BABYLOVE_API_KEY/);
  });

  it('logs the envelope keys when no shape matches, instead of failing blind', async () => {
    const fake = makeFakeD1();
    const errors: string[] = [];
    vi.spyOn(console, 'error').mockImplementation((line: unknown) => { errors.push(String(line)); });
    vi.stubGlobal('fetch', vi.fn().mockResolvedValueOnce(
      new Response(JSON.stringify({ payload: { nested: [] }, page: 1 }), { status: 200 }),
    ));

    await expect(reconcileBabyLoveArticles(env(fake.db, {
      BABYLOVE_AUTOPUBLISH_ENABLED: 'true',
      BABYLOVE_API_KEY: 'api-test-key',
      GITHUB_TOKEN: 'github-test-token',
    }))).rejects.toThrow('api_list_invalid');

    const logged = errors.find((line) => line.includes('babylove_reconciliation_list_invalid'));
    expect(logged).toBeDefined();
    expect(JSON.parse(logged as string).envelope_keys).toEqual(['payload', 'page']);
  });
});
