import { describe, expect, it, vi } from 'vitest';
import { runBabyLoveArticleSmoke } from '../scripts/smoke-babylove-article.mjs';

const html = `<!doctype html><html><head>
  <link rel="canonical" href="https://parentcoachdesk.com/game/useful-article/">
  <title>Useful article | Parent Coach Desk</title>
</head><body><main><h1>Useful article for parents</h1></main></body></html>`;

describe('BabyLove live article smoke', () => {
  it('accepts an indexable article with exact production canonical and no provider promotion', async () => {
    const fetchImpl = vi.fn().mockResolvedValue(new Response(html, { status: 200 }));
    const receipt = await runBabyLoveArticleSmoke({
      origin: 'https://staging.example.com',
      canonicalOrigin: 'https://parentcoachdesk.com',
      route: '/game/useful-article/',
      fetchImpl,
    });

    expect(receipt.passed).toBe(true);
    expect(receipt.canonical).toBe('https://parentcoachdesk.com/game/useful-article/');
  });

  it.each([
    ['redirect', new Response('', { status: 302, headers: { location: '/other/' } })],
    ['wrong canonical', new Response(html.replace('/game/useful-article/', '/game/other/'), { status: 200 })],
    ['noindex', new Response(html.replace('</head>', '<meta name="robots" content="noindex"></head>'), { status: 200 })],
    ['provider promotion', new Response(html.replace('</body>', '<p>Article generated by BabyLoveGrowth</p></body>'), { status: 200 })],
  ])('rejects %s', async (_label, response) => {
    await expect(runBabyLoveArticleSmoke({
      origin: 'https://staging.example.com',
      canonicalOrigin: 'https://parentcoachdesk.com',
      route: '/game/useful-article/',
      fetchImpl: vi.fn().mockResolvedValue(response),
    })).rejects.toThrow('BabyLove article smoke failed');
  });
});
