import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');

describe('BabyLoveGrowth publishing contract', () => {
  it('exposes a useful llms.txt without private or administrative routes', () => {
    const llms = readFileSync(resolve(root, 'public/llms.txt'), 'utf8');
    expect(llms).toContain('# Parent Coach Desk');
    expect(llms).toContain('https://parentcoachdesk.com/reads/');
    expect(llms).toContain('https://parentcoachdesk.com/body/');
    expect(llms).not.toMatch(/\/admin\/|api\/|blog\.parentcoachdesk\.com/);
  });

  it('defines a receipt ledger with a provider-scoped idempotency key', () => {
    const migration = readFileSync(
      resolve(root, 'migrations-pcd-ops/0029_external_article_receipts.sql'),
      'utf8',
    );
    expect(migration).toMatch(/CREATE TABLE(?: IF NOT EXISTS)? external_article_receipts/i);
    expect(migration).toMatch(/UNIQUE\s*\(provider, provider_article_id, payload_sha256\)/i);
    expect(migration).toContain("'retryable_failure'");
    expect(migration).toContain("'quarantined'");
  });

  it('keeps the hosted subdomain out of Worker configuration', () => {
    const production = readFileSync(resolve(root, 'wrangler.production.jsonc'), 'utf8');
    const staging = readFileSync(resolve(root, 'wrangler.jsonc'), 'utf8');
    for (const config of [production, staging]) {
      expect(config).toContain('/api/integrations/babylovegrowth/articles');
      expect(config).not.toContain('blog.parentcoachdesk.com');
    }
  });

  // The three workflows that used to carry this contract — babylove-normalize.yml,
  // deploy-workers.yml, and the protected `production` environment its release
  // classifier could auto-approve — were deleted on 2026-08-05 with the rest of
  // GitHub Actions. What survives is the ingest half: the Worker webhook still
  // writes published articles straight to origin/main. Nothing deploys them, and
  // nothing normalizes their frontmatter afterward, so both are asserted here as
  // deliberate facts rather than left as silent gaps.
  it('ingests provider articles through the Worker webhook, gated by a flag', () => {
    const lib = readFileSync(resolve(root, 'src/lib/babylove-growth.ts'), 'utf8');
    const production = readFileSync(resolve(root, 'wrangler.production.jsonc'), 'utf8');
    const staging = readFileSync(resolve(root, 'wrangler.jsonc'), 'utf8');

    // Ingest is a Worker route writing to GitHub, not a CI job.
    expect(lib).toContain("const PROVIDER = 'babylovegrowth'");
    expect(lib).toContain('BABYLOVE_AUTOPUBLISH_ENABLED');
    expect(lib).toMatch(/if \(!enabled\(env\.BABYLOVE_AUTOPUBLISH_ENABLED\)\)/);

    // The flag is the only thing separating the two environments' behavior.
    expect(production).toContain('"BABYLOVE_AUTOPUBLISH_ENABLED": "true"');
    expect(staging).toContain('"BABYLOVE_AUTOPUBLISH_ENABLED": "false"');
  });

  it('has no CI deploy or normalize step behind provider publishes', () => {
    for (const workflow of [
      '.github/workflows/babylove-normalize.yml',
      '.github/workflows/deploy-workers.yml',
    ]) {
      expect(() => readFileSync(resolve(root, workflow), 'utf8')).toThrow();
    }
  });

  // Discovered rather than hardcoded. This test used to name usa-vs-usssa-bats and
  // youth-sports-costs, and it broke silently on 2026-08-03 when commit 02f78b70
  // removed the provider tag from exactly those two articles. Enumerating the
  // collection means the contract follows the content instead of drifting from it.
  it('keeps provider provenance private while rejecting visible provider promotion', () => {
    const articlesDir = resolve(root, 'src/content/articles');
    const tagged = readdirSync(articlesDir)
      .filter((name) => name.endsWith('.md'))
      .map((name) => ({ name, source: readFileSync(resolve(articlesDir, name), 'utf8') }))
      .filter(({ source }) => source.includes('provider: "babylovegrowth"'));

    expect(tagged.length).toBeGreaterThan(0);

    for (const { name, source } of tagged) {
      // Provenance lives in frontmatter only, never as visible body copy.
      expect(source, name).not.toContain('Article generated by BabyLoveGrowth');
      expect(source, name).not.toMatch(/babylovegrowth\.ai/i);
      // Frontmatter must carry the id the affiliate pass keys its gap queue on.
      expect(source, name).toMatch(/articleId: "\d+"/);
    }
    // Explicit budget: this reads every file in the articles collection (~470 and
    // growing), which is well under a second on a local disk but takes ~7s when
    // the repo is on the Windows-mounted volume the Cowork agents run against.
    // The default 5s timeout failed there, not because anything was wrong.
  }, 30_000);
});
