#!/usr/bin/env node
// Backfill latitude/longitude for approved camps that are missing coordinates.
//
// Why: at submit time, Nominatim sometimes rate-limits or times out, leaving
// camps with NULL lat/lng. Those camps don't render on the map. This script
// finds them, re-geocodes against Nominatim with proper 1 req/sec politeness,
// and writes an UPDATE SQL file you apply via wrangler.
//
// Run from project root:
//
//   1. Dump the missing rows to JSON:
//      npx wrangler d1 execute parent-coach-playbook --remote --json \
//        --command "SELECT id, address, city, state, zip FROM camps WHERE status='approved' AND (latitude IS NULL OR longitude IS NULL)" \
//        > imports/.cache/missing-geo.json
//
//   2. Run this script:
//      node scripts/backfill-geocode.mjs imports/.cache/missing-geo.json
//
//   3. Apply the generated SQL:
//      npx wrangler d1 execute parent-coach-playbook --remote --file=imports/.cache/backfill-geocode.sql

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';

const ROOT = resolve(process.cwd());
const inputPath = process.argv[2];
if (!inputPath) {
  console.error('Usage: node scripts/backfill-geocode.mjs <missing-geo.json>');
  process.exit(1);
}

const SLEEP_MS = 1100; // Nominatim asks for ≤1 req/sec
const UA = 'parentcoachplaybook.com camps directory (parentcoachplaybook@gmail.com)';

async function geocode(address, city, state, zip) {
  const q = [address, city, state, zip].filter(Boolean).join(', ');
  const url = new URL('https://nominatim.openstreetmap.org/search');
  url.searchParams.set('q', q);
  url.searchParams.set('format', 'json');
  url.searchParams.set('limit', '1');

  const res = await fetch(url.toString(), {
    headers: { 'User-Agent': UA, 'Accept-Language': 'en' },
  });
  if (!res.ok) return { ok: false, status: res.status };
  const data = await res.json();
  if (!Array.isArray(data) || data.length === 0) return { ok: false, status: 'no_match' };
  const lat = Number.parseFloat(data[0].lat);
  const lon = Number.parseFloat(data[0].lon);
  if (!Number.isFinite(lat) || !Number.isFinite(lon)) return { ok: false, status: 'parse_error' };
  return { ok: true, lat, lon };
}

// Wrangler --json output is an array of result blocks. Find the rows.
const raw = JSON.parse(await readFile(inputPath, 'utf8'));
const rows = Array.isArray(raw) ? raw[0]?.results ?? raw[0] ?? [] : raw.results ?? [];
if (!rows.length) {
  console.error('No rows in', inputPath);
  process.exit(1);
}

console.log(`Backfilling ${rows.length} camps. ETA ~${Math.ceil((rows.length * SLEEP_MS) / 60000)} min.`);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const updates = [];
const fails = [];

for (let i = 0; i < rows.length; i += 1) {
  const r = rows[i];
  const label = `[${i + 1}/${rows.length}] ${r.city}, ${r.state}`;
  try {
    const result = await geocode(r.address || '', r.city || '', r.state || '', r.zip || '');
    if (result.ok) {
      updates.push(
        `UPDATE camps SET latitude = ${result.lat}, longitude = ${result.lon}, updated_at = datetime('now') WHERE id = '${r.id}';`,
      );
      console.log(`${label} → ${result.lat.toFixed(4)}, ${result.lon.toFixed(4)}`);
    } else {
      // Try a fallback query with just city/state/zip — addresses with venue names
      // (e.g. "Robert Morris Soccer Stadium") often fail; centroid is acceptable.
      const fallback = await geocode('', r.city || '', r.state || '', r.zip || '');
      if (fallback.ok) {
        updates.push(
          `UPDATE camps SET latitude = ${fallback.lat}, longitude = ${fallback.lon}, updated_at = datetime('now') WHERE id = '${r.id}';`,
        );
        console.log(`${label} → ${fallback.lat.toFixed(4)}, ${fallback.lon.toFixed(4)} (fallback)`);
        await sleep(SLEEP_MS); // extra sleep, made two calls
      } else {
        fails.push({ id: r.id, city: r.city, state: r.state, reason: result.status });
        console.log(`${label} → MISS (${result.status})`);
      }
    }
  } catch (e) {
    fails.push({ id: r.id, city: r.city, state: r.state, reason: String(e?.message || e) });
    console.log(`${label} → ERROR ${e?.message || e}`);
  }
  await sleep(SLEEP_MS);
}

const out = resolve(ROOT, 'imports/.cache/backfill-geocode.sql');
await mkdir(dirname(out), { recursive: true });
const header = [
  '-- Auto-generated by scripts/backfill-geocode.mjs',
  `-- Source: ${inputPath}`,
  `-- Resolved: ${updates.length} / ${rows.length}`,
  `-- Misses: ${fails.length}`,
  '',
];
await writeFile(out, header.concat(updates).join('\n') + '\n');

console.log(`\n✓ Wrote ${updates.length} UPDATE statements to ${out}`);
if (fails.length) {
  console.log(`✗ ${fails.length} still failed:`);
  for (const f of fails) console.log(`   ${f.id}  ${f.city}, ${f.state}  (${f.reason})`);
}
console.log('\nApply with:');
console.log(`  npx wrangler d1 execute parent-coach-playbook --remote --file="${out}"`);
