#!/usr/bin/env python3
"""
build_zip_centroids.py

Converts a free ZIP-centroid file into seed SQL for the zip_centroids table.
Geocoding orgs by ZIP needs no paid API: load this once, then a single UPDATE
join fills lat/lng for every org with a known ZIP.

SOURCE (free): the U.S. Census ZCTA national gazetteer. Download the latest
"ZIP Code Tabulation Areas" national file from:
  https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.html
It is a tab-delimited .txt inside a .zip, with columns GEOID, INTPTLAT, INTPTLONG.

This reader is format-tolerant: it auto-detects comma or tab delimiter and accepts
either the gazetteer columns (GEOID / INTPTLAT / INTPTLONG) or generic CSV columns
(zip / lat / lng), so any ZIP-centroid source works.

USAGE:
  python scripts/build_zip_centroids.py 2023_Gaz_zcta_national.txt --out seed/0007_zip_centroids.sql
  npx wrangler d1 execute activity-radar --remote --file=./seed/0007_zip_centroids.sql
"""

import argparse
import csv
import os
import sys


def pick(row_lc, *names):
    for n in names:
        if n in row_lc and str(row_lc[n]).strip() != "":
            return str(row_lc[n]).strip()
    return None


def sql_str(v):
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="ZIP centroid file (Census gazetteer .txt or a zip,lat,lng CSV)")
    ap.add_argument("--out", default="seed/0007_zip_centroids.sql")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    with open(args.input, encoding="utf-8-sig", newline="") as f:
        sample = f.read(4096)
        f.seek(0)
        delim = "\t" if sample.count("\t") >= sample.count(",") else ","
        reader = csv.DictReader(f, delimiter=delim)
        rows = {}
        for row in reader:
            rl = {k.lower().strip(): v for k, v in row.items() if k}
            z = pick(rl, "zip", "zipcode", "zcta", "zcta5", "geoid", "geoid20")
            lat = pick(rl, "lat", "latitude", "intptlat")
            lng = pick(rl, "lng", "lon", "long", "longitude", "intptlong")
            if not (z and lat and lng):
                continue
            z = z.strip().zfill(5)[:5]
            try:
                latf, lngf = float(lat), float(lng)
            except ValueError:
                continue
            rows[z] = (latf, lngf, pick(rl, "city"), pick(rl, "state", "usps"))

    print(f"parsed {len(rows)} ZIP centroids (delimiter={'tab' if delim==chr(9) else 'comma'})", file=sys.stderr)
    if args.dry_run:
        return

    lines = [
        "-- 0007_zip_centroids.sql",
        "-- Generated by scripts/build_zip_centroids.py.",
        f"-- {len(rows)} ZIP centroids.",
        "",
    ]
    for z, (lat, lng, city, state) in rows.items():
        lines.append(
            "INSERT OR REPLACE INTO zip_centroids (zip,latitude,longitude,city,state) VALUES ("
            + ",".join([sql_str(z), str(lat), str(lng), sql_str(city), sql_str(state)]) + ");"
        )
    lines.append("")

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {args.out} ({len(rows)} rows)", file=sys.stderr)


if __name__ == "__main__":
    main()
