-- One-time customer invitation and recovery challenges.
-- Tokens are generated by a future route/provider adapter and only hashes are stored.

CREATE TABLE customer_invitations (
  id TEXT PRIMARY KEY,
  organization_id TEXT NOT NULL REFERENCES customer_organizations(id),
  invited_email_normalized TEXT NOT NULL,
  proposed_role TEXT NOT NULL CHECK(proposed_role IN ('owner','admin','editor','viewer')),
  token_sha256 TEXT NOT NULL UNIQUE CHECK(length(token_sha256) = 64),
  invited_by_customer_user_id TEXT NOT NULL REFERENCES customer_users(id),
  status TEXT NOT NULL CHECK(status IN ('pending','accepted','revoked','expired')),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  accepted_at TEXT,
  accepted_by_customer_user_id TEXT REFERENCES customer_users(id),
  revoked_at TEXT,
  CHECK(invited_email_normalized = lower(trim(invited_email_normalized))),
  CHECK(status <> 'accepted' OR (accepted_at IS NOT NULL AND accepted_by_customer_user_id IS NOT NULL)),
  CHECK(status <> 'revoked' OR revoked_at IS NOT NULL)
);

CREATE INDEX idx_customer_invitations_pending
  ON customer_invitations(invited_email_normalized, status, expires_at);

CREATE TABLE customer_recovery_challenges (
  id TEXT PRIMARY KEY,
  customer_user_id TEXT NOT NULL REFERENCES customer_users(id),
  purpose TEXT NOT NULL CHECK(purpose IN ('account_recovery','email_change','step_up','identity_unlink')),
  token_sha256 TEXT NOT NULL UNIQUE CHECK(length(token_sha256) = 64),
  status TEXT NOT NULL CHECK(status IN ('pending','consumed','revoked','expired','locked')),
  attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 20),
  max_attempts INTEGER NOT NULL CHECK(max_attempts BETWEEN 1 AND 20),
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  revoked_at TEXT,
  request_context_hash TEXT NOT NULL CHECK(length(request_context_hash) = 64),
  CHECK(status <> 'consumed' OR consumed_at IS NOT NULL),
  CHECK(status <> 'revoked' OR revoked_at IS NOT NULL)
);

CREATE INDEX idx_customer_recovery_pending
  ON customer_recovery_challenges(customer_user_id, purpose, status, expires_at);

CREATE TABLE customer_security_events (
  id TEXT PRIMARY KEY,
  customer_user_id TEXT REFERENCES customer_users(id),
  organization_id TEXT REFERENCES customer_organizations(id),
  event_type TEXT NOT NULL,
  actor_type TEXT NOT NULL CHECK(actor_type IN ('customer','staff','provider','system')),
  actor_ref TEXT NOT NULL,
  outcome TEXT NOT NULL CHECK(outcome IN ('allowed','denied','failed','completed','revoked')),
  reason_code TEXT,
  context_hash TEXT,
  occurred_at TEXT NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE
);

CREATE INDEX idx_customer_security_events_user
  ON customer_security_events(customer_user_id, occurred_at);

-- Raw invitation/recovery tokens, passwords, provider session tokens, IP
-- addresses, and user-agent strings are intentionally absent.
